console.log("Hello world");
var a = 10;
var b = 20;
console.log("the addition of a and b is ", a+b);
console.log("the subtraction of a and b is ", a-b);
console.log("the multiplication of a and b is ", a*b);
console.log("the modulo of a and b is ", a%b);
console.log("the division of a and b is ", a/b);

console.log(true && true);
console.log(true && false);
console.log(false && false);
console.log(false && true);

var num = 87;
if(num>=1 && num<=30){
    console.log('E');
}
else if(num>=31 && num<=50){
    console.log('D');
}
else if(num>=51 && num<=60){
    console.log('C');
}
else if(num>=61 && num<=80){
    console.log('B');
}
else{
    console.log('A')
}

